package collector

import (
	"fmt"
	"sort"
	"strings"
)

// CurlInput holds the data needed to generate a curl command.
type CurlInput struct {
	Method     string
	URL        string
	Headers    map[string][]string
	Body       string
	HasBody    bool
	IsBinary   bool
	BinarySize int64
}

// curlExcludedHeaders are transport-level headers excluded from curl commands
// because they are either auto-generated by curl or not meaningful for replay.
var curlExcludedHeaders = map[string]bool{
	"Content-Length":    true,
	"Accept-Encoding":  true,
	"Connection":       true,
	"Host":             true,
	"Transfer-Encoding": true,
	"Upgrade":          true,
}

// BuildCurlCommand generates a multi-line curl command from the given input.
// It is a pure function with no side effects or I/O.
func BuildCurlCommand(input *CurlInput) string {
	if input == nil || input.URL == "" {
		return ""
	}

	var b strings.Builder

	// Method + URL
	method := strings.ToUpper(input.Method)
	if method == "" || method == "GET" {
		b.WriteString("curl")
	} else {
		b.WriteString(fmt.Sprintf("curl -X %s", method))
	}

	// URL (single-quoted for shell safety)
	b.WriteString(fmt.Sprintf(" '%s'", escapeSingleQuotes(input.URL)))

	// Headers (sorted alphabetically for deterministic output)
	headerKeys := make([]string, 0, len(input.Headers))
	for k := range input.Headers {
		if curlExcludedHeaders[k] {
			continue
		}
		headerKeys = append(headerKeys, k)
	}
	sort.Strings(headerKeys)

	for _, key := range headerKeys {
		for _, val := range input.Headers[key] {
			b.WriteString(fmt.Sprintf(" \\\n  -H '%s: %s'", escapeSingleQuotes(key), escapeSingleQuotes(val)))
		}
	}

	// Body
	if input.IsBinary {
		b.WriteString(fmt.Sprintf(" \\\n  # Body: binary data (%d bytes) - not included", input.BinarySize))
	} else if input.HasBody && input.Body != "" {
		b.WriteString(fmt.Sprintf(" \\\n  -d '%s'", escapeSingleQuotes(input.Body)))
	}

	return b.String()
}

// escapeSingleQuotes escapes single quotes for safe use in shell single-quoted strings.
// It uses the standard shell pattern: end quote, add escaped quote, restart quote.
// Example: "it's" → "it'\''s"
func escapeSingleQuotes(s string) string {
	return strings.ReplaceAll(s, "'", "'\\''")
}
